version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: churn
    ports: ["5432:5432"]
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/churn
    depends_on: [db]
    ports: ["8000:8000"]
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    depends_on: [api]
    ports: ["8501:8501"]
