processed_dir: data/processed
artifacts_dir: artifacts
reports_dir: reports

target: Churn
random_state: 42
cv_folds: 5
calibration_method: isotonic   # or "sigmoid"

# Baseline models (simple, fast defaults)
logreg:
  C: 1.0
  max_iter: 2000
  class_weight: balanced

xgboost:
  n_estimators: 400
  learning_rate: 0.05
  max_depth: 4
  subsample: 0.9
  colsample_bytree: 0.9
  reg_alpha: 0.0
  reg_lambda: 1.0
  tree_method: auto   # set "hist" if you like
